#!/bin/bash


if [[ ! $1 ]]; then
	echo "Need argument" >&2
	exit 1
fi

#while read -r || [[ $REPLY ]]; do
#	if [[ $REPLY =~ $1 ]]; then
#		echo "$REPLY"
#		break
#	fi
#done
#
#while read -r || [[ $REPLY ]]; do
#	echo "$REPLY"
#done

found=
while read -r || [[ $REPLY ]]; do
	if [[ ! $found ]]; then
		if [[ $REPLY =~ $1 ]]; then
			found="yep"
		else
			continue
		fi
	fi
	echo "$REPLY"
done
 
exit 0
